### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by jackysteps** [BenjaminFrazer/adf4368#1]
Would you please make a statement for license information about this repository?

Thanks

**Comment by BenjaminFrazer** [comment]
Hi Jack, I've added the MIT license to this project. 

I should mention that this API is still WIP and as of yet FULLY untested on actual hardware.  I have done extensive testing of the parameter engine and frequency selection using host testing and I'm pretty confident it will work in auto-calibration mode. Fast hopping mode may still need a bit more work. I think the framework I've written here, critically the parameter engine, will still be useful to anyone intending to extend the capabilities of the library. I'm very open to collaboration if you or others wish to do this.
